global:
  scrape_interval: 120s
  evaluation_interval: 120s

 # Rule files for alerts
rule_files:
  - "/etc/prometheus/rules/*.yml" 

scrape_configs:
  - job_name: 'pollutant-api'
    static_configs:
      - targets: ['app:9000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

