GradientBoosting_run_id: 39d8fa2938cc4af68fc06f7fa2fdfdfc
RandomForest_run_id: 9bb768f4f0f6402ea5419c41f8b98bdd
combined_data_path: data/processed/combined_data.csv
mlflow:
  experiment_name: Pollutant Prediction
  tracking_uri: http://localhost:5001
model_directory: model
model_filename: random_forest_model.pkl
model_params:
  max_depth: 15
  n_estimators: 250
n_lags: 4
run_id: 5d9dc45683054d62b675d2dc088916a3
start_year: 2020
target: Total_Release_Water
test_path: data/processed/test_processed.csv
train_path: data/processed/train_processed.csv
