global:
  scrape_interval: 60s  # Increased the scrape interval to 30 seconds globally
  evaluation_interval: 60s  # Increased the evaluation interval to 30 seconds globally

scrape_configs:
  - job_name: 'ml-api'
    scrape_interval: 10s  # Increased the scrape interval for ml-api to 10 seconds
    static_configs:
      - targets: ['app:9000']

  - job_name: 'prometheus'
    scrape_interval: 15s  # Increased the scrape interval for Prometheus itself to 15 seconds
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'model-training' 
    scrape_interval: 10s  # Increased the scrape interval to 10 seconds for model training
    static_configs:
      - targets:
        - 'training-metrics:8002'  # Ensure this target matches the server that exposes metrics
    metrics_path: /metrics  # Ensure the metrics path is /metrics for Prometheus to scrape
    scheme: http  # Ensure that HTTP is used to scrape the metrics
    scrape_timeout: 5s  # Increased the scrape timeout to 5 seconds to allow more time for scraping
